### PR TITLE
Redesign Post New Question Page

### PR DESCRIPTION
**Pull request by thekingslee**
- [x] Redesigned the post new question page
- [x] Rid console logs
- [x] Implement the new discussion page
- [x] Add tags to post question page
- [ ] Fix share on Qfeed and Discussion page

### CODE REVIEW

**Comment by nworiekingslee** [comment]
@devgenix

**Comment by devgenix** [comment]
@nworiekingslee add option to tag questions, adding tags should be done by typing a coma or enter

**Comment by nworiekingslee** [comment]
Is the doc on post man up to date?

**Comment by devgenix** [comment]
> Is the doc on post man up to date?
> 
> These tags will be individual strings?
> 
> 

They are. 

Yes you pass the tags as a string separated by coma or spaces and we'll take it up from there.

**Comment by nworiekingslee** [comment]
> > Is the doc on post man up to date?
> > These tags will be individual strings?
> 
> They are.
> 
> Yes you pass the tags as a string separated by coma or spaces and we'll take it up from there.

In this format ?
```
{
       tags : "geophysics, geoscience, mathematics"
}
```

**Comment by devgenix** [comment]
> > > Is the doc on post man up to date?
> > > These tags will be individual strings?
> > 
> > They are.
> > 
> > Yes you pass the tags as a string separated by coma or spaces and we'll take it up from there.
> 
> In this format ?
> ```
> {
>        tags : "geophysics, geoscience, mathematics"
> }
> ```

Yes

**Comment by devgenix** [comment]
> > > Is the doc on post man up to date?
> > > These tags will be individual strings?
> > 
> > They are.
> > 
> > Yes you pass the tags as a string separated by coma or spaces and we'll take it up from there.
> 
> In this format ?
> ```
> {
>        tags : "geophysics, geoscience, mathematics"
> }
> ```

Just check the Postman workspace. 
Also note that we automatically append # to tags if it doesn't already exist. What do you think about that?

**Review by devgenix — APPROVED** [review]

**Pull request merged**
