### PR TITLE
Model a ad

### PR DESCRIPTION
**Pull request by nworiekingslee**
# Description
- No new dependencies added
- Removed the personal-data-screen in the sign up flow
- Redirect user to update-school-data after log in if they didn't during sign up
- Fix the Airtable bug

Fixes # (issue)
- No known issue created
## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
- This have been tested on my local server to ensure correct behavior

- [ ] Test A
- [ ] Test B

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by devgenix — CHANGES_REQUESTED** [review]
Thanks for the great work, @nworiekingslee 

But I have a concern, if we've make the user to come back to update their school-data if they didn't during signup, doesn't that defeat the purpose of the skip button?

**Comment by devgenix** [comment]
@nworiekingslee also please check the merge conflict.

**Comment by nworiekingslee** [comment]
> Thanks for the great work, @nworiekingslee
> 
> But I have a concern, if we've make the user to come back to update their school-data if they didn't during signup, doesn't that defeat the purpose of the skip button?

How I think of it is, it's like a remembrance that they haven't provided the data yet. Or what do you think. I can remove the skip button.

The reason I added it is to make sure there is no blocker during the sign up

**Comment by devgenix** [comment]
> > Thanks for the great work, @nworiekingslee
> > But I have a concern, if we've make the user to come back to update their school-data if they didn't during signup, doesn't that defeat the purpose of the skip button?
> 
> How I think of it is, it's like a remembrance that they haven't provided the data yet. Or what do you think. I can remove the skip button.
> 
> The reason I added it is to make sure there is no blocker during the sign up

@nworiekingslee right now, it's like a circle. On skip, if takes a user to the app only to log them out again.

I think it's best we just remove it.

**Comment by devgenix** [comment]
@nworiekingslee Instead of removing it entirely, I suggest we use that to understand which Universities we should prioritize by replacing "skip" with "Make a request" and that should link to a form/place to allow them enter the name of their Insititution and we can use that to understand what schools are the most requested.

**Comment by nworiekingslee** [comment]
> @nworiekingslee Instead of removing it entirely, I suggest we use that to understand which Universities we should prioritize by replacing "skip" with "Make a request" and that should link to a form/place to allow them enter the name of their Insititution and we can use that to understand what schools are the most requested.

That would take a while. i think we should close the PR and work on that on another.

**Comment by devgenix** [comment]
> > @nworiekingslee Instead of removing it entirely, I suggest we use that to understand which Universities we should prioritize by replacing "skip" with "Make a request" and that should link to a form/place to allow them enter the name of their Insititution and we can use that to understand what schools are the most requested.
> 
> That would take a while. i think we should close the PR and work on that on another.

I agree. I'll merge this now.

**Review by devgenix — APPROVED** [review]

**Pull request merged**
