### PR TITLE
UI Changes #256

### PR DESCRIPTION
**Pull request by jomefavourite**
- Warn: Changes I can't remember why
- fixed login and signup page
- fixed bookmark not updated of discussion
- finally fixed bookmark for discussion and qfeed ibelieve

### CODE REVIEW

**Comment by devgenix** [comment]
> - Warn: Changes I can't remember why
> - fixed login and signup page
> - fixed bookmark not updated of discussion
> - finally fixed bookmark for discussion and qfeed ibelieve
> 
> 

All tested and these have been addressed.

**Comment by devgenix** [comment]
@jomefavourite 

Issues left; 

- Add an icon for close/question.

**Comment by jomefavourite** [comment]
> @jomefavourite
> 
> Issues left;
> 
> * Add an icon for close/question.

@nworiekingslee mentioned he'll work on this, so I didn't

**Comment by devgenix** [comment]
> > @jomefavourite
> > 
> > Issues left;
> > 
> > * Add an icon for close/question.
> 
> @nworiekingslee mentioned he'll work on this, so I didn't

He's yet to and he's had weeks to do it but didn't, please work on it.

**Comment by nworiekingslee** [comment]
Let me tag you to the icons to use @jomefavourite

**Comment by jomefavourite** [comment]
> Let me tag you to the icons to use @jomefavourite

Okay

**Comment by nworiekingslee** [comment]
> > Let me tag you to the icons to use @jomefavourite
> 
> Okay

I have tagged you

**Comment by devgenix** [comment]
> I've added the close and open icon @devgenix Though, I noticed on an echoed question, closing and saving a question goes to the endpoint but doesn't reflect on the UI

Can you explain further? Is it reflected in the response?

**Comment by devgenix** [comment]
> > I've added the close and open icon @devgenix Though, I noticed on an echoed question, closing and saving a question goes to the endpoint but doesn't reflect on the UI
> 
> Can you explain further? Is it reflected in the response?

@jomefavourite waiting for your reply on this.

**Comment by nworiekingslee** [comment]
Screenshot 2023-04-13 at 23 31 29


I fixed this issue @jomefavourite. I will push it to #262

**Comment by jomefavourite** [comment]
> Screenshot 2023-04-13 at 23 31 29
> 
> I fixed this issue @jomefavourite. I will push it to #262

Okay, noted

**Comment by jomefavourite** [comment]
> 

Done

**Comment by devgenix** [comment]
> It's done @devgenix

Good to go.

**Pull request merged**
