### PR TITLE
Fix: Discussion Page Redesign

### PR DESCRIPTION
**Pull request by nworiekingslee**
This PR fixes bugs on comment section. And mades some fixes based on recommendation.

- Hide Loadmore after clicked ✅
-   Show loading for 3rd level ✅ 
- On Mobile screen, put the editor btns on the bottom within React Quill ✅
-   Dismiss RTE on 2nd level after a successful send ✅ 
- Add Lazy Loading ✅
- Redesigned the Discussion page ✅
- Add Verification Badge everywhere it would be needed✅

### CODE REVIEW

**Comment by devgenix** [comment]
> @devgenix 

Please kindly outline with bullet points what this PR does.

**Comment by devgenix** [comment]
> > @devgenix
> 
> Please kindly outline with bullet points what this PR does.

@nworiekingslee Waiting for you on this.

**Comment by nworiekingslee** [comment]
This PR fixes bugs on comment section. And mades some fixes based on recommendation.

**Comment by nworiekingslee** [comment]
> > @devgenix
> 
> Please kindly outline with bullet points what this PR does.

I have renamed the PR name to reflect what changes it brings

**Comment by nworiekingslee** [comment]
@devgenix

**Comment by devgenix** [comment]
> > > @devgenix
> > 
> > Please kindly outline with bullet points what this PR does.
> 
> I have renamed the PR name to reflect what changes it brings

Please also add a description as to what and what was done, listing then by how many they are.

**Comment by nworiekingslee** [comment]
> This PR fixes bugs on comment section. And mades some fixes based on recommendation.
> 
> * Hide Loadmore after clicked ✅
> * Show loading for 3rd level ✅
> * On Mobile screen, put the editor btns on the bottom within React Quill ✅
> * Dismiss RTE on 2nd level after a successful send ✅
> * Add Lazy Loading ✅

@devgenix

**Comment by devgenix** [comment]
> This PR fixes bugs on comment section. And mades some fixes based on recommendation.
> 
>     * Hide Loadmore after clicked ✅
> 
>     * Show loading for 3rd level ✅
> 
>     * On Mobile screen, put the editor btns on the bottom within React Quill ✅
> 
>     * Dismiss RTE on 2nd level after a successful send ✅
> 
>     * Add Lazy Loading ✅
> 
>     * Redesigned the Discussion page ✅
> 
>     * Add Verification Badge everywhere it would be needed✅

For reference, here's where you'd ideally describe what the PR does.

**Comment by devgenix** [comment]
> This PR fixes bugs on comment section. And mades some fixes based on recommendation.
> 
>     * Hide Loadmore after clicked ✅
> 
>     * Show loading for 3rd level ✅
> 
>     * On Mobile screen, put the editor btns on the bottom within React Quill ✅
> 
>     * Dismiss RTE on 2nd level after a successful send ✅
> 
>     * Add Lazy Loading ✅
> 
>     * Redesigned the Discussion page ✅
> 
>     * Add Verification Badge everywhere it would be needed✅

I've tested and verified that the following are done;

- [x] Add Lazy Loading ✅
- [x] Hide Loadmore after clicked ✅
- [x] Dismiss RTE on 2nd level after a successful send ✅ 
- [x] Add Verification Badge everywhere it would be needed✅
- [x] On Mobile screen, put the editor btns on the bottom within React Quill ✅
- [x] Redesigned the Discussion page ✅
- [x] Hide Loadmore after clicked ✅  
- [x] Add Verification Badge everywhere it would be needed✅

However there are some issues left;

- [ ] lazy loading is not working when you expand third-level replies ( Show loading for 3rd level )
- [ ] Optimistic vote is not present for question in discussion page

**Comment by nworiekingslee** [comment]
Okay. I did

> > This PR fixes bugs on comment section. And mades some fixes based on recommendation.
> > ```
> > * Hide Loadmore after clicked ✅
> > 
> > * Show loading for 3rd level ✅
> > 
> > * On Mobile screen, put the editor btns on the bottom within React Quill ✅
> > 
> > * Dismiss RTE on 2nd level after a successful send ✅
> > 
> > * Add Lazy Loading ✅
> > 
> > * Redesigned the Discussion page ✅
> > 
> > * Add Verification Badge everywhere it would be needed✅
> > ```
> 
> I've tested and verified that the following are done;
> 
> * [x]  Add Lazy Loading ✅
> * [x]  Hide Loadmore after clicked ✅
> * [x]  Dismiss RTE on 2nd level after a successful send ✅
> * [x]  Add Verification Badge everywhere it would be needed✅
> * [x]  On Mobile screen, put the editor btns on the bottom within React Quill ✅
> * [x]  Redesigned the Discussion page ✅
> * [x]  Hide Loadmore after clicked ✅
> * [x]  Add Verification Badge everywhere it would be needed✅
> 
> However there are some issues left;
> 
> * [ ]  lazy loading is not working when you expand third-level replies ( Show loading for 3rd level )
> * [ ]  Optimistic vote is not present for question in discussion page


Can we merge this, while I work on the remaining fixes on a later time. Could be weekend

**Comment by devgenix** [comment]
> Okay. 
> 
> > > This PR fixes bugs on comment section. And mades some fixes based on recommendation.
> > > ```
> > > * Hide Loadmore after clicked ✅
> > > 
> > > * Show loading for 3rd level ✅
> > > 
> > > * On Mobile screen, put the editor btns on the bottom within React Quill ✅
> > > 
> > > * Dismiss RTE on 2nd level after a successful send ✅
> > > 
> > > * Add Lazy Loading ✅
> > > 
> > > * Redesigned the Discussion page ✅
> > > 
> > > * Add Verification Badge everywhere it would be needed✅
> > > ```
> > 
> > I've tested and verified that the following are done;
> > 
> > * [x]  Add Lazy Loading ✅
> > * [x]  Hide Loadmore after clicked ✅
> > * [x]  Dismiss RTE on 2nd level after a successful send ✅
> > * [x]  Add Verification Badge everywhere it would be needed✅
> > * [x]  On Mobile screen, put the editor btns on the bottom within React Quill ✅
> > * [x]  Redesigned the Discussion page ✅
> > * [x]  Hide Loadmore after clicked ✅
> > * [x]  Add Verification Badge everywhere it would be needed✅
> > 
> > However there are some issues left;
> > 
> > * [ ]  lazy loading is not working when you expand third-level replies ( Show loading for 3rd level )
> > * [ ]  Optimistic vote is not present for question in discussion page
> 
> 
> Can we merge this, while I work on the remaining fixes on a later time. Could be weekend
> 

Urgh, the issues left directly concerns this PR and for every outlined fix/feature you worked on in this - PR, it should be end-to-end. Meaning it should be all done and when this PR is merged we know it's complete.

**Comment by nworiekingslee** [comment]
Okay. I modify and remove the 3rd level loading from the list. There a bug causing it to work sometimes and not work other time. It's not a straight forward bug to fix. I need to keep moving, so that we can achieve as much as we can. 

I have also added some more commits, making other fixes from around the app.

**Review by devgenix — APPROVED** [review]

**Pull request merged**
